FROM clojure

ENV app_path=/opt/tw
ENV app_name=infra-problem

RUN test -n "$app_path"
RUN test -n "$app_name"

RUN apt -y update && apt -y upgrade
RUN apt -y install make python3

RUN mkdir -p $app_path && cd $app_path && git clone https://github.com/ThoughtWorksInc/infra-problem.git 
RUN cd ${app_path}/${app_name} && make libs && make clean all

#CMD ${app_path}/${app_name}/front-end/public/serve.py && java -jar ${app_path}/${app_name}/build/front-end.jar
